global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
